{
 "title": "Media Server Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Service Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Plex Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_info == 1", "legendFormat": "{{version}}" }
   ]
  },
  { "title": "Media Library Sizes", "gridPos": { "h": 8, "w": 7, "x": 6, "y": 1 } },
  { "title": "Media Library Free Space", "gridPos": { "h": 8, "w": 5, "x": 13, "y": 1 } },
  { "title": "Media Server System Status", "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 } },
  { "title": "Lidarr Missing vs. Downloaded", "gridPos": { "h": 5, "w": 4, "x": 6, "y": 9 } },
  { "title": "Sonarr Missing vs. Downloaded", "gridPos": { "h": 5, "w": 4, "x": 10, "y": 9 } },
  { "title": "Radarr Missing vs. Downloaded", "gridPos": { "h": 5, "w": 4, "x": 14, "y": 9 } },
  { "title": "Service Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Streams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plex_sessions_count{state!=\"paused\"})"
    }
   ]
  },
  {
   "title": "Transcodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plex_video_transcode_sessions_count{state!=\"paused\"})"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plex_media_downloads_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Library Movements",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "delta(plex_media_count[1d] offset 1d)",
     "legendFormat": "{{ title }}"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(plex_video_transcode_sessions_count{state!=\"paused\"})",
     "legendFormat": "Transcodes"
    },
    {
     "expr": "sum(plex_sessions_count{state!=\"paused\"})",
     "legendFormat": "Streams"
    },
    {
     "expr": "sum(plex_media_downloads_count) > 0",
     "legendFormat": "Downloads"
    }
   ]
  },
  {
   "title": "Download Durations",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum_over_time(plex_media_downloads_count[$__range]) > 0)",
     "legendFormat": "{{ username }}"
    }
   ]
  }
 ]
}